name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: Analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run tests and generate coverage report
      run: npm test -- --coverage

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        token: ${{ secrets.SONAR_TOKEN }}
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_SCANNER_OPTS: '-Dsonar.javascript.lcov.reportPaths=coverage/lcov-report/lcov-report.json'

    