name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: Analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
    # Checkout do repositório
    - name: Checkout code
      uses: actions/checkout@v2

    # Configurar Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    # Instalar dependências
    - name: Install dependencies
      run: npm install

    # Rodar os testes (opcional, mas recomendado)
    - name: Run tests
      run: npm test

    # Rodar o scanner do SonarQube
    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        token: ${{ secrets.SONAR_TOKEN }}
        projectName: 'sonarqube-demo'
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    