name: Demo

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18.x
            - run: npm install
            - run: npm test
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            - run: |
                npm install -g sonar-scanner
                sonar-scanner \
                    -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
                    -Dsonar.projectKey=sonarqube-demo
                    -Dsonar.sources=src
                    -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
