name: Demo

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18.x
            - run: npm ci
            - run: npm test
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: "http://localhost:9000"

            - run: |
                    npm install -g sonar-scanner
                    sonar-scanner \
                    -X \
                    -Dsonar.projectKey=sonarqube-demo \
                    -Dsonar.sources=. \
                    -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
